# AQC v0.1.0 -- ExplorationRoundTrip(descriptor): descriptor -> node ->
# descriptor identity (the G2 seam, now a contract law -- spec §2). At the
# WIRE level this is graph_wire::encode_node_id/decode_node_id's own
# bijection: the id a FocusQuery/TraversalQuery response hands back always
# re-resolves the SAME node when fed straight back into FocusQuery.
#
# The Examples: table is GENERATED by the same exporter as focus-query.feature
# (server/atlas-server/src/bins/export_aqc_examples.rs) -- one seed id per real
# node kind, verified live against the committed graph.
Feature: ExplorationRoundTrip -- descriptor -> node -> descriptor identity

  Scenario Outline: a captured focus reference round-trips identically
    Given a node of kind "<kind>" with id "<id>"
    When I run FocusQuery for "<id>"
    And I capture the returned focus reference
    And I run FocusQuery again for the captured reference
    Then the focus reference round-trips identically

    Examples:
      | kind           | id                             |
      | TextUnit       | text-unit:JHN.3.16             |
      | Event          | Event:ab_ur                    |
      | Narrative      | Narrative:abraham-migration    |
      | Anchor         | Anchor:solomon-crowned         |
      | Place          | Place:ur-1                     |
      | Era            | Era:primeval                   |
      | Polity         | Polity:egypt                   |
      | Person         | Person:aaron_1                 |
      | Translation    | Translation:latin_vulgate      |
      | CommentaryItem | CommentaryItem:kretzmann/0.1.0 |
      | CatechismItem  | CatechismItem:commandment-1    |

  Scenario: a traversal target's own id round-trips too
    Given a node of kind "TextUnit" with id "text-unit:JHN.3.16"
    When I run TraversalQuery for "text-unit:JHN.3.16" frontier "cites"
    And I capture the returned focus reference
    And I run FocusQuery again for the captured reference
    Then the focus reference round-trips identically
