pub const SEEDS: &[(&str, &str)] = &[
    ("TextUnit", "text-unit:JHN.3.16"),
    ("Event", "Event:ab_ur"),
    ("Narrative", "Narrative:abraham-migration"),
    ("Anchor", "Anchor:solomon-crowned"),
    ("Place", "Place:ur-1"),
    ("Era", "Era:primeval"),
    ("Polity", "Polity:egypt"),
    ("Person", "Person:aaron_1"),
    ("Translation", "Translation:latin_vulgate"),
    ("CommentaryItem", "CommentaryItem:kretzmann/0.1.0"),
    ("CatechismItem", "CatechismItem:commandment-1"),
];

pub const FOCUS_IDENTITY_EXTRA: &[(&str, &str)] = &[("text-unit:ROM.5.8", "focus-traversal-target")];

pub const FIXTURES: &[(&str, &str)] = &[
    ("focus-not-found", "/api/node/Person:nonexistent-xyz"),
    ("focus-bad-ref", "/api/node/not-even-a-colon-pair"),
    ("focus-traversal-target", "/api/node/text-unit:ROM.5.8"),
    ("traversal-cites", "/api/node/text-unit:JHN.3.16/edges?kind=cites"),
    ("traversal-cites-limit1", "/api/node/text-unit:JHN.3.16/edges?kind=cites&limit=1"),
    ("traversal-located-at", "/api/node/Event:ab_ur/edges?kind=located-at"),
    ("traversal-bad-kind", "/api/node/text-unit:JHN.3.16/edges?kind=not-a-real-kind"),
    ("text-window-single", "/api/text?ref=JHN.3.16&n=1"),
    ("text-window-multi", "/api/text?ref=JHN.3.16&n=3"),
    ("text-window-mat-4-19", "/api/text?ref=MAT.4.19&n=1"),
    ("text-window-mat-5-4", "/api/text?ref=MAT.5.4&n=1"),
    ("text-window-chapter-backward-bad-dir", "/api/text?ref=JHN.3&scope=chapter&dir=backward"),
    ("text-window-bad-corpus", "/api/text?ref=JHN.3.16&n=1&corpus=not-a-real-corpus"),
    ("text-window-bad-scope", "/api/text?ref=JHN.3.16&n=1&scope=not-a-real-scope"),
    ("text-window-concord-chapter-bad-scope", "/api/text?ref=BoC%207.2.1&corpus=concord&scope=chapter"),
    ("place-period-bad-window", "/api/place/hazor-1?from=notayear"),
    ("scene-time", "/api/scene?from=-2100&to=-2000"),
    ("scene-scripture", "/api/scene/scripture?ref=JHN.3.16"),
    ("scene-bad-window", "/api/scene?from=100&to=-100"),
    ("scene-bad-ref", "/api/scene/scripture?ref=not-a-ref-at-all"),
    ("contents-bible", "/api/contents/bible"),
    ("contents-concord", "/api/contents/concord"),
    ("contents-bad-corpus", "/api/contents/nope"),
    ("contract", "/api/contract"),
];

/// Percent-encodes the one wire-id character that collides with axum's own
/// path-segment routing (`/`, as in `CommentaryItem:kretzmann/0.1.0`).
pub fn path_encode(id: &str) -> String {
    id.replace('/', "%2F")
}

pub fn examples_table(indent: &str) -> String {
    let kind_w = SEEDS.iter().map(|(k, _)| k.len()).chain(["kind".len()]).max().unwrap();
    let id_w = SEEDS.iter().map(|(_, i)| i.len()).chain(["id".len()]).max().unwrap();
    let mut out = String::new();
    out.push_str(&format!("{indent}| {:<kind_w$} | {:<id_w$} |\n", "kind", "id"));
    for (kind, id) in SEEDS {
        out.push_str(&format!("{indent}| {kind:<kind_w$} | {id:<id_w$} |\n"));
    }
    out
}

pub fn focus_query_feature() -> String {
    format!(
        r#"# FocusQuery(descriptor) -> one node's card.
# GET /api/node/{{id}} -- server/atlas-contract/src/graph.rs::node_card.
#
# The Examples: table below is GENERATED, not hand-authored -- see
# server/atlas-contract/src/bins/export_aqc_examples.rs. It draws one seed id per
# NODE KIND the real committed graph materializes, verified live against that
# graph at export time, so a stale seed id fails the exporter loud rather than
# silently. Re-running the exporter against an unchanged graph reproduces this
# table byte-identical; nothing in it is wall-clock random.
Feature: FocusQuery -- one node's card, by descriptor

  Scenario Outline: every sampled node kind resolves to a valid Focus card
    Given a node of kind "<kind>" with id "<id>"
    When I run FocusQuery for "<id>"
    Then the response is a valid "NodeCard"
    And the response "id" field equals "<id>"
    And the response "kind" field equals "<kind>"
    And every frontier group is a relations! family

    Examples:
{examples}
  Scenario: an id that parses but names no real node is not_found
    Given a node of kind "Person" with id "Person:nonexistent-xyz"
    When I run FocusQuery for "Person:nonexistent-xyz"
    Then the request fails with status 404 and code "not_found"

  Scenario: a malformed id is bad_ref
    When I run FocusQuery for "not-even-a-colon-pair"
    Then the request fails with status 400 and code "bad_ref"
"#,
        examples = examples_table("      ")
    )
}

pub fn exploration_roundtrip_feature() -> String {
    format!(
        r#"# ExplorationRoundTrip(descriptor): descriptor -> node -> descriptor
# identity. At the WIRE level this is the node-id encoding's own bijection: the
# id a FocusQuery or TraversalQuery response hands back always re-resolves the
# SAME node when fed straight back into FocusQuery.
#
# The Examples: table is GENERATED by the same exporter as focus-query.feature
# (server/atlas-contract/src/bins/export_aqc_examples.rs) -- one seed id per real
# node kind, verified live against the committed graph.
Feature: ExplorationRoundTrip -- descriptor -> node -> descriptor identity

  Scenario Outline: a captured focus reference round-trips identically
    Given a node of kind "<kind>" with id "<id>"
    When I run FocusQuery for "<id>"
    And I capture the returned focus reference
    And I run FocusQuery again for the captured reference
    Then the focus reference round-trips identically

    Examples:
{examples}
  Scenario: a traversal target's own id round-trips too
    Given a node of kind "TextUnit" with id "text-unit:JHN.3.16"
    When I run TraversalQuery for "text-unit:JHN.3.16" frontier "cites"
    And I capture the returned focus reference
    And I run FocusQuery again for the captured reference
    Then the focus reference round-trips identically
"#,
        examples = examples_table("      ")
    )
}
