//! The published contract documents, all of them derived from the Rust that
//! serves the API (spec D8). `contracts/openapi.yaml` is the contract; the
//! Atlas Query Contract's shapes and the Atlas Graph Contract's vocabulary
//! fixture are derivations of it at their own committed paths.

use std::path::PathBuf;

use atlas_graph_types::{NodeKind, RelationId, SymRelationId};
use serde::Serialize;
use serde_json::{json, Value};
use utoipa::openapi::extensions::ExtensionsBuilder;
use utoipa::openapi::{Info, OpenApi};

const GENERATED_BY: &str = "# Generated by `cargo run -p atlas-contract --bin export_contract` from the Rust that serves it; do not edit.
";
const API_TITLE: &str = "Bible Atlas API";
const API_DESCRIPTION: &str = "The Bible Atlas HTTP API, generated from the Rust that serves it.";
const RELATIONS_EXTENSION: &str = "x-atlas-relations";
const COMPONENT_REFERENCE: &str = "#/components/schemas/";
const SHAPE_REFERENCE: &str = "#/$defs/";

/// One published document: where it is committed, and the Rust that renders
/// it. Pairing the two in one value is what keeps a document from being
/// published to a path nothing renders, or rendered to no path at all.
pub struct GeneratedDocument {
    /// Relative to `contracts_root()`.
    pub path: &'static str,
    pub render: fn() -> String,
}

/// Every document the exporter publishes, declared once. A document that
/// stops being generated is a promise quietly withdrawn, so this list is the
/// one place it exists -- the exporter, the gate and the byte-identity test
/// all read it rather than restate it.
pub const GENERATED_DOCUMENTS: [GeneratedDocument; 3] = [
    GeneratedDocument { path: "openapi.yaml", render: openapi_yaml },
    GeneratedDocument { path: "atlas-query-contract/aqc.schema.json", render: aqc_schema_json },
    GeneratedDocument { path: "atlas-graph-contract/fixtures/graph-vocabulary.json", render: graph_vocabulary_json },
];

pub fn generated_files() -> Vec<(PathBuf, String)> {
    GENERATED_DOCUMENTS.iter().map(|document| (contracts_root().join(document.path), (document.render)())).collect()
}

pub fn contracts_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../contracts")
}

pub fn openapi_yaml() -> String {
    GENERATED_BY.to_string() + &openapi().to_yaml().expect("the OpenAPI document serialises")
}

/// The router's document, named and versioned as the PUBLISHED contract:
/// left alone it carries utoipa-axum's own crate metadata (that crate's
/// title, author and licence), which would be published as though it
/// described this API.
pub fn openapi() -> OpenApi {
    let mut doc = crate::openapi();
    let mut info = Info::new(API_TITLE, crate::meta::MAX_SUPPORTED_VERSION);
    info.description = Some(API_DESCRIPTION.to_string());
    doc.info = info;
    doc.extensions = Some(ExtensionsBuilder::new().add(RELATIONS_EXTENSION, relations_json()).build());
    doc
}

pub fn relations_json() -> Value {
    json!({
        "directed": RelationId::ALL.iter().map(|r| json!({"name": format!("{r:?}"), "forward": r.forward_label(), "inverse": r.inverse_label()})).collect::<Vec<_>>(),
        "symmetric": SymRelationId::ALL.iter().map(|s| json!({"name": format!("{s:?}"), "label": s.label()})).collect::<Vec<_>>(),
    })
}

/// The shapes both Atlas Query Contract harnesses validate responses
/// against. They resolve a shape as `#/$defs/<Shape>`, which is where a
/// JSON Schema document keeps its definitions; the OpenAPI document keeps
/// the same schemas under `#/components/schemas/`, so every reference is
/// rewritten to the one the harnesses follow.
pub fn aqc_schema_json() -> String {
    let doc = serde_json::to_value(openapi()).expect("the document serialises to JSON");
    let mut shapes = doc["components"]["schemas"].clone();
    point_references_at_shapes(&mut shapes);
    let out = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://bible-atlas/contracts/atlas-query-contract/aqc.schema.json",
        "title": "Atlas Query Contract -- shapes",
        "description": "Derived from contracts/openapi.yaml by export_contract; do not edit.",
        "version": crate::meta::MAX_SUPPORTED_VERSION,
        "$defs": shapes,
    });
    serde_json::to_string_pretty(&out).expect("the AQC schema serialises") + "\n"
}

fn point_references_at_shapes(value: &mut Value) {
    match value {
        Value::Object(map) => {
            for (key, child) in map.iter_mut() {
                match child.as_str() {
                    Some(target) if key == "$ref" => *child = Value::String(target.replace(COMPONENT_REFERENCE, SHAPE_REFERENCE)),
                    _ => point_references_at_shapes(child),
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(point_references_at_shapes),
        _ => {}
    }
}

pub fn graph_vocabulary_json() -> String {
    let relations = relations_json();
    blessed_fixture(&json!({
        "manifest_schema": atlas_graph::sqlite::manifest::MANIFEST_SCHEMA,
        "section_schema_version": atlas_graph::sections::SECTION_SCHEMA_VERSION,
        "node_kinds": NodeKind::ALL.iter().map(|k| k.name()).collect::<Vec<_>>(),
        "relations": relations["directed"],
        "symmetric": relations["symmetric"],
    }))
}

/// The Atlas Graph Contract's runner blesses a fixture with aeson-pretty --
/// four-space indent, no trailing newline. This fixture is now blessed from
/// both sides, so it renders the runner's way; otherwise the two blessers
/// would rewrite each other's whitespace and one gate would always be red.
fn blessed_fixture(value: &Value) -> String {
    let mut rendered = Vec::new();
    let mut serializer = serde_json::Serializer::with_formatter(&mut rendered, serde_json::ser::PrettyFormatter::with_indent(b"    "));
    value.serialize(&mut serializer).expect("a fixture serialises");
    String::from_utf8(rendered).expect("serde_json emits UTF-8")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_component_reference_becomes_a_defs_reference_at_every_depth() {
        // Arrange
        let mut shapes = json!({
            "NodeCard": { "properties": { "kind": { "$ref": "#/components/schemas/NodeKind" } } },
            "Position": { "oneOf": [{ "$ref": "#/components/schemas/PositionKind" }] },
        });
        // Act
        point_references_at_shapes(&mut shapes);
        // Assert
        assert_eq!(
            shapes,
            json!({
                "NodeCard": { "properties": { "kind": { "$ref": "#/$defs/NodeKind" } } },
                "Position": { "oneOf": [{ "$ref": "#/$defs/PositionKind" }] },
            })
        );
    }

    #[test]
    fn a_value_that_is_not_a_reference_keeps_the_component_path_it_merely_names() {
        // Arrange
        let mut shapes = json!({ "NodeCard": { "description": "the same shape OpenAPI keeps at #/components/schemas/NodeCard" } });
        // Act
        point_references_at_shapes(&mut shapes);
        // Assert
        assert_eq!(shapes, json!({ "NodeCard": { "description": "the same shape OpenAPI keeps at #/components/schemas/NodeCard" } }));
    }
}
