use std::path::PathBuf;

use atlas_core::time;
use atlas_graph_types::{NodeKind, RelationId, SymRelationId};
use serde::Serialize;
use serde_json::{json, Value};
use utoipa::openapi::extensions::ExtensionsBuilder;
use utoipa::openapi::schema::{AdditionalProperties, Schema, SchemaType, Type};
use utoipa::openapi::tag::TagBuilder;
use utoipa::openapi::{Info, OpenApi, RefOr};

use crate::wire::{DateClaim, TimeRange, Year};

const GENERATED_BY: &str = "# Generated by `cargo run -p atlas-contract --bin export_contract` from the Rust that serves it; do not edit.
";
const API_TITLE: &str = "Bible Atlas API";
const API_DESCRIPTION: &str = "The Bible Atlas HTTP API, generated from the Rust that serves it. The `x-atlas-relations` extension lists every relation this atlas joins two nodes by, each with the label its forward and its inverse frontier is asked for, so a consumer builds its own frontier vocabulary from that list rather than writing one out.";
const RELATIONS_EXTENSION: &str = "x-atlas-relations";
const COMPONENT_REFERENCE: &str = "#/components/schemas/";
const SHAPE_REFERENCE: &str = "#/$defs/";

/// The eight families every route belongs to, as a consumer's table of contents.
/// A route names its own family where it is declared; this list gives each name
/// its one sentence, and the families a route may name are exactly these.
pub const FAMILIES: [(&str, &str); 8] = [
    ("meta", "What this server is: whether it is up, the range of contract versions it answers for, this document itself, and the sources every answer is drawn from."),
    ("map", "The map: what is in view for a span of years or at a passage, the polity borders and eras behind it, and the coastline and landmarks it is drawn over."),
    ("reading", "Scripture as it is read: a chapter verse by verse, one verse in full, and the cross references a verse carries."),
    ("catechism", "The catechism: one item in full, and the items that cite a passage."),
    ("places", "One place: where it is, what happened there, and the name and history it bore in the period asked about."),
    ("events", "What happened: one event in full, every narrative this atlas tells, and the narrative legs an event belongs to."),
    ("graph", "This atlas as a graph: one node's card, one frontier of its neighbours, and a window of a corpus's reading spine."),
    ("contents", "One corpus's table of contents, two levels deep."),
];

/// One published document: where it is committed, and the Rust that renders it.
/// Pairing the two keeps a document from being published to a path nothing
/// renders, or rendered to no path at all.
pub struct GeneratedDocument {
    /// Relative to `contracts_root()`.
    pub path: &'static str,
    pub render: fn() -> String,
}

/// One published document as it stands rendered: the file it belongs at, and the
/// bytes that belong in it.
#[derive(Debug, PartialEq)]
pub struct RenderedDocument {
    pub path: PathBuf,
    pub contents: String,
}

pub const GENERATED_DOCUMENTS: [GeneratedDocument; 4] = [
    GeneratedDocument { path: "openapi.yaml", render: openapi_yaml },
    GeneratedDocument { path: "atlas-query-contract/aqc.schema.json", render: aqc_schema_json },
    GeneratedDocument { path: "atlas-graph-contract/fixtures/graph-vocabulary.json", render: graph_vocabulary_json },
    GeneratedDocument { path: "atlas-query-contract/vectors/year-labels.json", render: year_labels_json },
];

pub fn generated_files() -> Vec<RenderedDocument> {
    GENERATED_DOCUMENTS.iter().map(|document| RenderedDocument { path: contracts_root().join(document.path), contents: (document.render)() }).collect()
}

pub fn contracts_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../contracts")
}

pub fn openapi_yaml() -> String {
    GENERATED_BY.to_string() + &openapi().to_yaml().expect("the OpenAPI document serialises")
}

/// The router's document, named and versioned as the PUBLISHED contract: left
/// alone it carries utoipa-axum's own crate metadata, which would be published
/// as though it described this API.
pub fn openapi() -> OpenApi {
    let mut doc = crate::openapi();
    let mut info = Info::new(API_TITLE, crate::meta::MAX_SUPPORTED_VERSION);
    info.description = Some(API_DESCRIPTION.to_string());
    doc.info = info;
    doc.tags = Some(FAMILIES.iter().map(|(name, description)| TagBuilder::new().name(*name).description(Some(*description)).build()).collect());
    doc.extensions = Some(ExtensionsBuilder::new().add(RELATIONS_EXTENSION, relations_json()).build());
    close_every_object(&mut doc);
    doc
}

/// Every object this document publishes is closed. The wire carries only the
/// fields a served struct declares, because serialising one emits no others;
/// saying so once here rather than on each struct leaves the structs that also
/// READ a data file free to go on reading whatever that file carries.
fn close_every_object(doc: &mut OpenApi) {
    for schema in doc.components.iter_mut().flat_map(|components| components.schemas.values_mut()) {
        if let RefOr::T(Schema::Object(object)) = schema {
            if matches!(object.schema_type, SchemaType::Type(Type::Object)) && object.additional_properties.is_none() {
                object.additional_properties = Some(Box::new(AdditionalProperties::FreeForm(false)));
            }
        }
    }
}

pub fn relations_json() -> Value {
    json!({
        "directed": RelationId::ALL.iter().map(|r| json!({"name": r.name(), "forward": r.forward_label(), "inverse": r.inverse_label()})).collect::<Vec<_>>(),
        "symmetric": SymRelationId::ALL.iter().map(|s| json!({"name": s.name(), "label": s.label()})).collect::<Vec<_>>(),
    })
}

/// The shapes the Atlas Query Contract harnesses validate responses against.
/// They resolve a shape as `#/$defs/<Shape>`, where a JSON Schema document keeps
/// its definitions, so every component reference is rewritten to that path.
pub fn aqc_schema_json() -> String {
    let doc = serde_json::to_value(openapi()).expect("the document serialises to JSON");
    let mut shapes = doc["components"]["schemas"].clone();
    point_references_at_shapes(&mut shapes);
    strip_prose_from_each(&mut shapes);
    let out = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://bible-atlas/contracts/atlas-query-contract/aqc.schema.json",
        "title": "Atlas Query Contract -- shapes",
        "description": "Derived from contracts/openapi.yaml by export_contract; do not edit.",
        "version": crate::meta::MAX_SUPPORTED_VERSION,
        "$defs": shapes,
    });
    serde_json::to_string_pretty(&out).expect("the AQC schema serialises") + "\n"
}

fn point_references_at_shapes(value: &mut Value) {
    match value {
        Value::Object(map) => {
            for (key, child) in map.iter_mut() {
                match child.as_str() {
                    Some(target) if key == "$ref" => *child = Value::String(target.replace(COMPONENT_REFERENCE, SHAPE_REFERENCE)),
                    _ => point_references_at_shapes(child),
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(point_references_at_shapes),
        _ => {}
    }
}

const PROSE: [&str; 2] = ["description", "summary"];
const NAMED_BY_THE_SHAPE: [&str; 1] = ["properties"];

/// The harnesses read shapes, so prose is left to `openapi.yaml` alone: an edited
/// sentence then cannot ratchet the contract version those harnesses pin.
fn strip_prose_from_each(shapes: &mut Value) {
    members(shapes).for_each(strip_prose);
}

/// Under a keyword whose members the shape itself names -- `properties`, where a
/// field may well BE called `description` -- the names are not keywords, so the
/// removal resumes one level deeper instead of running at that level.
fn strip_prose(value: &mut Value) {
    match value {
        Value::Object(map) => {
            map.retain(|key, _| !PROSE.contains(&key.as_str()));
            for (key, child) in map.iter_mut() {
                match NAMED_BY_THE_SHAPE.contains(&key.as_str()) {
                    true => members(child).for_each(strip_prose),
                    false => strip_prose(child),
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(strip_prose),
        _ => {}
    }
}

fn members(value: &mut Value) -> impl Iterator<Item = &mut Value> {
    value.as_object_mut().into_iter().flat_map(|map| map.values_mut())
}

pub fn graph_vocabulary_json() -> String {
    let relations = relations_json();
    blessed_fixture(&json!({
        "manifest_schema": atlas_graph::sqlite::manifest::MANIFEST_SCHEMA,
        "section_schema_version": atlas_graph::sections::SECTION_SCHEMA_VERSION,
        "node_kinds": NodeKind::ALL.iter().map(|k| k.name()).collect::<Vec<_>>(),
        "relations": relations["directed"],
        "symmetric": relations["symmetric"],
    }))
}

/// The Atlas Graph Contract's runner blesses this fixture with aeson-pretty --
/// four-space indent, no trailing newline -- so rendering it any other way would
/// leave the two blessers rewriting each other's whitespace.
fn blessed_fixture(value: &Value) -> String {
    let mut rendered = Vec::new();
    let mut serializer = serde_json::Serializer::with_formatter(&mut rendered, serde_json::ser::PrettyFormatter::with_indent(b"    "));
    value.serialize(&mut serializer).expect("a fixture serialises");
    String::from_utf8(rendered).expect("serde_json emits UTF-8")
}

/// The labels a client that reads years back from what a reader types must agree
/// with, each written out beside the years it labels.
pub fn year_labels_json() -> String {
    let years: Vec<Year> = VECTOR_YEARS.iter().map(|value| Year::of(*value).expect("no vector year is zero")).collect();
    let ranges: Vec<Value> = VECTOR_RANGES.iter().map(|range| TimeRange::of(*range)).map(|range| json!({"from": range.from.value, "to": range.to.value, "label": range.label})).collect();
    let claims: Vec<Value> = VECTOR_CLAIMS
        .iter()
        .map(|claim| DateClaim::of(TimeRange::of(claim.when), Vec::new(), claim.note.map(str::to_string), None))
        .map(|claim| json!({"from": claim.when.from.value, "to": claim.when.to.value, "note": claim.note, "label": claim.label}))
        .collect();
    serde_json::to_string_pretty(&json!({"years": years, "ranges": ranges, "claims": claims})).expect("the year-label vectors serialise") + "\n"
}

const VECTOR_YEARS: [i32; 8] = [-4004, -1447, -1, 1, 30, 33, 100, 2000];

const VECTOR_RANGES: [time::TimeRange; 7] = [
    time::TimeRange { from_year: -1450, to_year: -1400 },
    time::TimeRange { from_year: -1447, to_year: -1400 },
    time::TimeRange { from_year: -1447, to_year: -1447 },
    time::TimeRange { from_year: -5, to_year: 30 },
    time::TimeRange { from_year: 33, to_year: 33 },
    time::TimeRange { from_year: 1, to_year: 100 },
    time::TimeRange { from_year: 30, to_year: 70 },
];

const VECTOR_CLAIMS: [ClaimVector; 3] = [
    ClaimVector { when: time::TimeRange { from_year: -1003, to_year: -1003 }, note: Some(TRADITIONAL) },
    ClaimVector { when: time::TimeRange { from_year: -586, to_year: -586 }, note: None },
    ClaimVector { when: time::TimeRange { from_year: -1447, to_year: -1400 }, note: Some(TRADITIONAL) },
];

const TRADITIONAL: &str = "traditional";

struct ClaimVector {
    when: time::TimeRange,
    note: Option<&'static str>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_component_reference_becomes_a_defs_reference_at_every_depth() {
        // Arrange
        let mut shapes = json!({
            "NodeCard": { "properties": { "kind": { "$ref": "#/components/schemas/NodeKind" } } },
            "Position": { "oneOf": [{ "$ref": "#/components/schemas/PositionKind" }] },
        });
        // Act
        point_references_at_shapes(&mut shapes);
        // Assert
        assert_eq!(
            shapes,
            json!({
                "NodeCard": { "properties": { "kind": { "$ref": "#/$defs/NodeKind" } } },
                "Position": { "oneOf": [{ "$ref": "#/$defs/PositionKind" }] },
            })
        );
    }

    #[test]
    fn a_value_that_is_not_a_reference_keeps_the_component_path_it_merely_names() {
        // Arrange
        let mut shapes = json!({ "NodeCard": { "description": "the same shape OpenAPI keeps at #/components/schemas/NodeCard" } });
        // Act
        point_references_at_shapes(&mut shapes);
        // Assert
        assert_eq!(shapes, json!({ "NodeCard": { "description": "the same shape OpenAPI keeps at #/components/schemas/NodeCard" } }));
    }

    #[test]
    fn a_shape_loses_its_prose_at_every_depth_and_keeps_the_field_that_is_called_description() {
        // Arrange
        let mut shapes = json!({
            "NodeCard": {
                "description": "One node of the graph at a glance.",
                "properties": {
                    "description": { "type": "string", "description": "Prose about this node." },
                    "edge_summary": { "type": "array", "items": { "type": "string", "summary": "One kind." } },
                },
            },
        });
        // Act
        strip_prose_from_each(&mut shapes);
        // Assert
        assert_eq!(
            shapes,
            json!({
                "NodeCard": {
                    "properties": {
                        "description": { "type": "string" },
                        "edge_summary": { "type": "array", "items": { "type": "string" } },
                    },
                },
            })
        );
    }
}
