use std::path::PathBuf;

use atlas_core::data::{Canon, CanonBook};
use atlas_core::time;
use atlas_graph_types::text::{BibleLocusRange, Locus, VerseRef};
use atlas_graph_types::edge::{Direction, EdgeKind};
use atlas_graph_types::{NodeKind, RelationId, SymRelationId};
use serde::Serialize;
use serde_json::{json, Value};
use utoipa::openapi::extensions::ExtensionsBuilder;
use utoipa::openapi::schema::{AdditionalProperties, Schema, SchemaType, Type};
use utoipa::openapi::tag::TagBuilder;
use utoipa::openapi::{Info, OpenApi, RefOr};

use crate::wire::{DateClaim, TextSpan, TimeRange, Year};

const GENERATED_BY: &str = "# Generated by `cargo run -p atlas-contract --bin export_contract` from the Rust that serves it; do not edit.
";
const API_TITLE: &str = "Bible Atlas API";
const AQC_VERSION: &str = include_str!("../../../contracts/atlas-query-contract/VERSION").trim_ascii();
const API_DESCRIPTION: &str = "The Bible Atlas HTTP API, generated from the Rust that serves it. The `x-atlas-relations` extension lists every relation this atlas joins two nodes by, each with the label its forward and its inverse neighbours are asked for and the words each is displayed by, so a consumer builds its own vocabulary from that list rather than writing one out.";
const RELATIONS_EXTENSION: &str = "x-atlas-relations";
const COMPONENT_REFERENCE: &str = "#/components/schemas/";
const SHAPE_REFERENCE: &str = "#/$defs/";

/// The eight families every route belongs to, as a consumer's table of contents.
/// A route names its own family where it is declared; this list gives each name
/// its one sentence, and the families a route may name are exactly these.
pub const FAMILIES: [(&str, &str); 8] = [
    ("meta", "What this server is: whether it is up, the schema versions of the data it answers from, this document itself, and the sources every answer is drawn from."),
    ("map", "The map: what is in view for a span of years or at a passage, the polity borders and eras behind it, and the coastline and landmarks it is drawn over."),
    ("reading", "Scripture as it is read: a chapter verse by verse, one verse in full, and the cross references a verse carries."),
    ("catechism", "The catechism: one item in full, and the items that cite a passage."),
    ("places", "One place: where it is, what happened there, and the name and history it bore in the period asked about."),
    ("events", "What happened: one event in full, every narrative this atlas tells, and the narrative legs an event belongs to."),
    ("graph", "This atlas as a graph: one node's record, nodes and edges by id many at once, one page of the neighbours of a node or an edge, and a window of a corpus's reading spine."),
    ("contents", "One corpus's table of contents, two levels deep."),
];

/// One published document: where it is committed, and the Rust that renders it.
/// Pairing the two keeps a document from being published to a path nothing
/// renders, or rendered to no path at all.
pub struct GeneratedDocument {
    /// Relative to `contracts_root()`.
    pub path: &'static str,
    pub render: fn() -> String,
}

/// One published document as it stands rendered: the file it belongs at, and the
/// bytes that belong in it.
#[derive(Debug, PartialEq)]
pub struct RenderedDocument {
    pub path: PathBuf,
    pub contents: String,
}

pub const GENERATED_DOCUMENTS: [GeneratedDocument; 7] = [
    GeneratedDocument { path: "openapi.yaml", render: openapi_yaml },
    GeneratedDocument { path: "atlas-query-contract/aqc.schema.json", render: aqc_schema_json },
    GeneratedDocument { path: "atlas-graph-contract/fixtures/graph-vocabulary.json", render: graph_vocabulary_json },
    GeneratedDocument { path: "atlas-query-contract/vectors/year-labels.json", render: year_labels_json },
    GeneratedDocument { path: "atlas-query-contract/vectors/attestation-runs.json", render: attestation_runs_json },
    GeneratedDocument { path: "atlas-query-contract/vectors/mention-spans.json", render: mention_spans_json },
    GeneratedDocument { path: "atlas-query-contract/vectors/citation-grammar.json", render: citation_grammar_json },
];

pub fn generated_files() -> Vec<RenderedDocument> {
    GENERATED_DOCUMENTS.iter().map(|document| RenderedDocument { path: contracts_root().join(document.path), contents: (document.render)() }).collect()
}

pub fn contracts_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../contracts")
}

pub fn openapi_yaml() -> String {
    GENERATED_BY.to_string() + &openapi().to_yaml().expect("the OpenAPI document serialises")
}

/// The router's document, named and versioned as the PUBLISHED contract: left
/// alone it carries utoipa-axum's own crate metadata, which would be published
/// as though it described this API.
pub fn openapi() -> OpenApi {
    let mut doc = crate::openapi();
    let mut info = Info::new(API_TITLE, AQC_VERSION);
    info.description = Some(API_DESCRIPTION.to_string());
    doc.info = info;
    doc.tags = Some(FAMILIES.iter().map(|(name, description)| TagBuilder::new().name(*name).description(Some(*description)).build()).collect());
    doc.extensions = Some(ExtensionsBuilder::new().add(RELATIONS_EXTENSION, relations_json()).build());
    close_every_object(&mut doc);
    doc
}

/// Every object this document publishes is closed. The wire carries only the
/// fields a served struct declares, because serialising one emits no others;
/// saying so once here rather than on each struct leaves the structs that also
/// READ a data file free to go on reading whatever that file carries.
fn close_every_object(doc: &mut OpenApi) {
    for schema in doc.components.iter_mut().flat_map(|components| components.schemas.values_mut()) {
        if let RefOr::T(Schema::Object(object)) = schema {
            if matches!(object.schema_type, SchemaType::Type(Type::Object)) && object.additional_properties.is_none() {
                object.additional_properties = Some(Box::new(AdditionalProperties::FreeForm(false)));
            }
        }
    }
}

pub fn relations_json() -> Value {
    json!({
        "directed": RelationId::ALL
            .iter()
            .map(|r| json!({
                "name": r.name(),
                "forward": r.forward_label(),
                "inverse": r.inverse_label(),
                "forward_display": EdgeKind::Directed(*r, Direction::Forward).display_label(),
                "inverse_display": EdgeKind::Directed(*r, Direction::Inverse).display_label(),
            }))
            .collect::<Vec<_>>(),
        "symmetric": SymRelationId::ALL.iter().map(|s| json!({"name": s.name(), "label": s.label(), "display": EdgeKind::Symmetric(*s).display_label()})).collect::<Vec<_>>(),
    })
}

/// The shapes the Atlas Query Contract harnesses validate responses against.
/// They resolve a shape as `#/$defs/<Shape>`, where a JSON Schema document keeps
/// its definitions, so every component reference is rewritten to that path.
pub fn aqc_schema_json() -> String {
    let doc = serde_json::to_value(openapi()).expect("the document serialises to JSON");
    let mut shapes = doc["components"]["schemas"].clone();
    point_references_at_shapes(&mut shapes);
    strip_prose_from_each(&mut shapes);
    let out = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://bible-atlas/contracts/atlas-query-contract/aqc.schema.json",
        "title": "Atlas Query Contract -- shapes",
        "description": "Derived from contracts/openapi.yaml by export_contract; do not edit.",
        "version": AQC_VERSION,
        "$defs": shapes,
    });
    serde_json::to_string_pretty(&out).expect("the AQC schema serialises") + "\n"
}

fn point_references_at_shapes(value: &mut Value) {
    match value {
        Value::Object(map) => {
            for (key, child) in map.iter_mut() {
                match (key.as_str(), child) {
                    ("$ref", reference @ Value::String(_)) => point_at_shape(reference),
                    ("mapping", Value::Object(subtypes)) => subtypes.values_mut().for_each(point_at_shape),
                    (_, child) => point_references_at_shapes(child),
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(point_references_at_shapes),
        _ => {}
    }
}

fn point_at_shape(reference: &mut Value) {
    if let Value::String(target) = reference {
        *target = target.replace(COMPONENT_REFERENCE, SHAPE_REFERENCE);
    }
}

const PROSE: [&str; 2] = ["description", "summary"];
const NAMED_BY_THE_SHAPE: [&str; 1] = ["properties"];

/// The harnesses read shapes, so prose is left to `openapi.yaml` alone: an edited
/// sentence then cannot ratchet the contract version those harnesses pin.
fn strip_prose_from_each(shapes: &mut Value) {
    members(shapes).for_each(strip_prose);
}

/// Under a keyword whose members the shape itself names -- `properties`, where a
/// field may well BE called `description` -- the names are not keywords, so the
/// removal resumes one level deeper instead of running at that level.
fn strip_prose(value: &mut Value) {
    match value {
        Value::Object(map) => {
            map.retain(|key, _| !PROSE.contains(&key.as_str()));
            for (key, child) in map.iter_mut() {
                match NAMED_BY_THE_SHAPE.contains(&key.as_str()) {
                    true => members(child).for_each(strip_prose),
                    false => strip_prose(child),
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(strip_prose),
        _ => {}
    }
}

fn members(value: &mut Value) -> impl Iterator<Item = &mut Value> {
    value.as_object_mut().into_iter().flat_map(|map| map.values_mut())
}

pub fn graph_vocabulary_json() -> String {
    let relations = relations_json();
    blessed_fixture(&json!({
        "manifest_schema": atlas_graph::sqlite::manifest::MANIFEST_SCHEMA,
        "section_schema_version": atlas_graph::sections::SECTION_SCHEMA_VERSION,
        "node_kinds": NodeKind::ALL.iter().map(|k| k.name()).collect::<Vec<_>>(),
        "relations": relations["directed"],
        "symmetric": relations["symmetric"],
    }))
}

/// The Atlas Graph Contract's runner blesses this fixture with aeson-pretty --
/// four-space indent, no trailing newline -- so rendering it any other way would
/// leave the two blessers rewriting each other's whitespace.
fn blessed_fixture(value: &Value) -> String {
    let mut rendered = Vec::new();
    let mut serializer = serde_json::Serializer::with_formatter(&mut rendered, serde_json::ser::PrettyFormatter::with_indent(b"    "));
    value.serialize(&mut serializer).expect("a fixture serialises");
    String::from_utf8(rendered).expect("serde_json emits UTF-8")
}

pub fn year_labels_json() -> String {
    let years: Vec<Year> = VECTOR_YEARS.iter().map(|value| Year::of(*value).expect("no vector year is zero")).collect();
    let ranges: Vec<Value> = VECTOR_RANGES.iter().map(|range| TimeRange::of(*range)).map(|range| json!({"from": range.from.value, "to": range.to.value, "label": range.label})).collect();
    let claims: Vec<Value> = VECTOR_CLAIMS
        .iter()
        .map(|claim| DateClaim::of(TimeRange::of(claim.when), Vec::new(), claim.note.map(str::to_string), None))
        .map(|claim| json!({"from": claim.when.from.value, "to": claim.when.to.value, "note": claim.note, "label": claim.label}))
        .collect();
    serde_json::to_string_pretty(&json!({"years": years, "ranges": ranges, "claims": claims})).expect("the year-label vectors serialise") + "\n"
}

const VECTOR_YEARS: [i32; 8] = [-4004, -1447, -1, 1, 30, 33, 100, 2000];

const VECTOR_RANGES: [time::TimeRange; 7] = [
    time::TimeRange { from_year: -1450, to_year: -1400 },
    time::TimeRange { from_year: -1447, to_year: -1400 },
    time::TimeRange { from_year: -1447, to_year: -1447 },
    time::TimeRange { from_year: -5, to_year: 30 },
    time::TimeRange { from_year: 33, to_year: 33 },
    time::TimeRange { from_year: 1, to_year: 100 },
    time::TimeRange { from_year: 30, to_year: 70 },
];

const VECTOR_CLAIMS: [ClaimVector; 3] = [
    ClaimVector { when: time::TimeRange { from_year: -1003, to_year: -1003 }, note: Some(TRADITIONAL) },
    ClaimVector { when: time::TimeRange { from_year: -586, to_year: -586 }, note: None },
    ClaimVector { when: time::TimeRange { from_year: -1447, to_year: -1400 }, note: Some(TRADITIONAL) },
];

const TRADITIONAL: &str = "traditional";

struct ClaimVector {
    when: time::TimeRange,
    note: Option<&'static str>,
}

pub fn mention_spans_json() -> String {
    serde_json::to_string_pretty(&json!({"cases": MENTION_CASES})).expect("the mention-span vectors serialise") + "\n"
}

#[derive(Serialize)]
struct MentionCase {
    name: &'static str,
    text: &'static str,
    places: &'static [NamedEntity],
    persons: &'static [NamedEntity],
    mentions: &'static [FoundMention],
}

#[derive(Serialize)]
struct NamedEntity {
    id: &'static str,
    name: &'static str,
}

#[derive(Serialize)]
struct FoundMention {
    start: usize,
    end: usize,
    kind: MentionKind,
    id: &'static str,
}

#[derive(Serialize)]
#[serde(rename_all = "lowercase")]
enum MentionKind {
    Place,
    Person,
}

const NO_NAMES: &[NamedEntity] = &[];
const NO_MENTIONS: &[FoundMention] = &[];
const JERUSALEM: NamedEntity = NamedEntity { id: "jerusalem", name: "Jerusalem" };

const MENTION_CASES: [MentionCase; 13] = [
    MentionCase {
        name: "a_text_with_no_names_to_search_mentions_nothing",
        text: "In the beginning God created the heaven.",
        places: NO_NAMES,
        persons: NO_NAMES,
        mentions: NO_MENTIONS,
    },
    MentionCase { name: "an_empty_text_mentions_nothing", text: "", places: &[JERUSALEM], persons: NO_NAMES, mentions: NO_MENTIONS },
    MentionCase {
        name: "a_name_inside_the_text_is_one_mention",
        text: "Abram dwelt in Hebron by the plain of Mamre.",
        places: &[NamedEntity { id: "hebron", name: "Hebron" }],
        persons: NO_NAMES,
        mentions: &[FoundMention { start: 15, end: 21, kind: MentionKind::Place, id: "hebron" }],
    },
    MentionCase {
        name: "a_name_at_the_very_start_is_found",
        text: "Jerusalem was besieged.",
        places: &[JERUSALEM],
        persons: NO_NAMES,
        mentions: &[FoundMention { start: 0, end: 9, kind: MentionKind::Place, id: "jerusalem" }],
    },
    MentionCase {
        name: "a_name_at_the_very_end_is_found",
        text: "They came to Jericho",
        places: &[NamedEntity { id: "jericho", name: "Jericho" }],
        persons: NO_NAMES,
        mentions: &[FoundMention { start: 13, end: 20, kind: MentionKind::Place, id: "jericho" }],
    },
    MentionCase { name: "differently_cased_text_never_matches", text: "go up to JERUSALEM now.", places: &[JERUSALEM], persons: NO_NAMES, mentions: NO_MENTIONS },
    MentionCase {
        name: "exactly_cased_text_still_matches",
        text: "go up to Jerusalem now.",
        places: &[JERUSALEM],
        persons: NO_NAMES,
        mentions: &[FoundMention { start: 9, end: 18, kind: MentionKind::Place, id: "jerusalem" }],
    },
    MentionCase {
        name: "two_names_apart_are_both_found",
        text: "From Bethlehem to Jerusalem is a short journey.",
        places: &[JERUSALEM, NamedEntity { id: "bethlehem", name: "Bethlehem" }],
        persons: NO_NAMES,
        mentions: &[
            FoundMention { start: 5, end: 14, kind: MentionKind::Place, id: "bethlehem" },
            FoundMention { start: 18, end: 27, kind: MentionKind::Place, id: "jerusalem" },
        ],
    },
    MentionCase {
        name: "longer_containing_name_wins_over_a_shorter_substring_name",
        text: "They journeyed to Beersheba and rested.",
        places: &[NamedEntity { id: "beersheba", name: "Beersheba" }, NamedEntity { id: "sheba", name: "Sheba" }],
        persons: NO_NAMES,
        mentions: &[FoundMention { start: 18, end: 27, kind: MentionKind::Place, id: "beersheba" }],
    },
    MentionCase {
        name: "unmatched_place_is_simply_absent_not_an_error",
        text: "The LORD spake unto Moses.",
        places: &[NamedEntity { id: "egypt", name: "Egypt" }],
        persons: NO_NAMES,
        mentions: NO_MENTIONS,
    },
    MentionCase {
        name: "place_name_longer_than_text_never_throws",
        text: "Ur",
        places: &[NamedEntity { id: "mesopotamia", name: "Mesopotamia" }],
        persons: NO_NAMES,
        mentions: NO_MENTIONS,
    },
    MentionCase {
        name: "a_person_is_found_as_a_place_is",
        text: "And Abram went down into Egypt.",
        places: &[NamedEntity { id: "egypt", name: "Egypt" }],
        persons: &[NamedEntity { id: "abram", name: "Abram" }],
        mentions: &[
            FoundMention { start: 4, end: 9, kind: MentionKind::Person, id: "abram" },
            FoundMention { start: 25, end: 30, kind: MentionKind::Place, id: "egypt" },
        ],
    },
    MentionCase {
        name: "a_name_both_a_place_and_a_person_bear_goes_to_the_place",
        text: "The queen of Sheba heard.",
        places: &[NamedEntity { id: "sheba", name: "Sheba" }],
        persons: &[NamedEntity { id: "sheba_1", name: "Sheba" }],
        mentions: &[FoundMention { start: 13, end: 18, kind: MentionKind::Place, id: "sheba" }],
    },
];

pub fn citation_grammar_json() -> String {
    let named = atlas_graph::citations::book_names().into_iter().map(|(name, book)| {
        let text = format!("{name} {FIRST}:{FIRST}");
        json!({
            "name": format!("a_citation_naming_{}", name.to_lowercase().replace(' ', "_")),
            "citations": [{ "start": 0, "end": text.chars().count(), "cites": format!("{}.{FIRST}.{FIRST}", book.code()) }],
            "text": text,
        })
    });
    let cases: Vec<Value> = CITATION_CASES.iter().map(|case| json!(case)).chain(named).collect();
    serde_json::to_string_pretty(&json!({"cases": cases})).expect("the citation-grammar vectors serialise") + "\n"
}

const FIRST: u16 = 1;

#[derive(Serialize)]
struct CitationCase {
    name: &'static str,
    text: &'static str,
    citations: &'static [FoundCitation],
}

#[derive(Serialize)]
struct FoundCitation {
    start: usize,
    end: usize,
    cites: &'static str,
}

const NO_CITATIONS: &[FoundCitation] = &[];

const CITATION_CASES: [CitationCase; 20] = [
    CitationCase { name: "plain_prose_cites_nothing", text: "We believe, teach, and confess.", citations: NO_CITATIONS },
    CitationCase {
        name: "an_abbreviation_its_period_a_chapter_and_a_verse",
        text: "As Christ says, Matt. 5:3, blessed are the poor.",
        citations: &[FoundCitation { start: 16, end: 25, cites: "MAT.5.3" }],
    },
    CitationCase { name: "a_book_named_in_full", text: "For God so loved the world, John 3:16.", citations: &[FoundCitation { start: 28, end: 37, cites: "JHN.3.16" }] },
    CitationCase { name: "a_numbered_book", text: "Of the Sacrament, 1 Cor. 11:23.", citations: &[FoundCitation { start: 18, end: 30, cites: "1CO.11.23" }] },
    CitationCase { name: "a_range_keeps_its_whole_range", text: "Obey the rulers, Rom. 13:1-4.", citations: &[FoundCitation { start: 17, end: 28, cites: "ROM.13.1-4" }] },
    CitationCase { name: "a_comma_may_part_the_chapter_from_the_verse", text: "Kiss the Son, Ps. 2, 12.", citations: &[FoundCitation { start: 14, end: 23, cites: "PSA.2.12" }] },
    CitationCase {
        name: "the_period_after_an_abbreviation_may_be_left_out",
        text: "He led captivity captive, Eph 4:8.",
        citations: &[FoundCitation { start: 26, end: 33, cites: "EPH.4.8" }],
    },
    CitationCase {
        name: "a_longer_name_wins_over_the_shorter_it_begins_with",
        text: "Charity suffereth long, 1 Corinthians 13:4.",
        citations: &[FoundCitation { start: 24, end: 42, cites: "1CO.13.4" }],
    },
    CitationCase { name: "an_ambiguous_abbreviation_cites_nothing", text: "Paul planted, Cor. 3:6; have this mind, Phil. 2:5.", citations: NO_CITATIONS },
    CitationCase { name: "an_unlisted_abbreviation_cites_nothing", text: "Woe unto him that striveth, Is. 45:9.", citations: NO_CITATIONS },
    CitationCase { name: "a_name_inside_a_longer_word_cites_nothing", text: "Regen. 1:1 is no book.", citations: NO_CITATIONS },
    CitationCase { name: "names_are_matched_in_their_own_case", text: "As it is written, matt. 5:3.", citations: NO_CITATIONS },
    CitationCase {
        name: "two_citations_in_one_text_are_both_found",
        text: "Gal. 1:8 and Matt. 7:15 warn us.",
        citations: &[FoundCitation { start: 0, end: 8, cites: "GAL.1.8" }, FoundCitation { start: 13, end: 23, cites: "MAT.7.15" }],
    },
    CitationCase { name: "a_range_that_runs_backward_cites_nothing", text: "See Matt. 5:9-3.", citations: NO_CITATIONS },
    CitationCase {
        name: "and_following_after_the_verse_is_inside_the_citation_which_cites_the_stated_verse_only",
        text: "Love is the fulfilling, Rom. 13:8f.",
        citations: &[FoundCitation { start: 24, end: 34, cites: "ROM.13.8" }],
    },
    CitationCase {
        name: "a_doubled_and_following_is_inside_the_citation_too",
        text: "Of the Law, Rom. 7:14ff, it is written.",
        citations: &[FoundCitation { start: 12, end: 23, cites: "ROM.7.14" }],
    },
    CitationCase {
        name: "the_latin_and_following_is_inside_the_citation_too",
        text: "The apostles in Acts 15:10sqq. strove.",
        citations: &[FoundCitation { start: 16, end: 29, cites: "ACT.15.10" }],
    },
    CitationCase {
        name: "letters_after_the_verse_that_are_no_and_following_are_left_outside_the_citation",
        text: "Love is the fulfilling, Rom. 13:8fold.",
        citations: &[FoundCitation { start: 24, end: 33, cites: "ROM.13.8" }],
    },
    CitationCase {
        name: "chapters_and_verses_run_to_three_digits",
        text: "Thy word is a lamp, Ps. 119:105.",
        citations: &[FoundCitation { start: 20, end: 31, cites: "PSA.119.105" }],
    },
    CitationCase { name: "offsets_count_characters_not_bytes", text: "Christ’s own word, John 3:16.", citations: &[FoundCitation { start: 19, end: 28, cites: "JHN.3.16" }] },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_component_reference_becomes_a_defs_reference_at_every_depth() {
        // Arrange
        let mut shapes = json!({
            "NodeRecord": { "properties": { "kind": { "$ref": "#/components/schemas/NodeKind" } } },
            "Position": { "oneOf": [{ "$ref": "#/components/schemas/PositionRef" }] },
        });
        // Act
        point_references_at_shapes(&mut shapes);
        // Assert
        assert_eq!(
            shapes,
            json!({
                "NodeRecord": { "properties": { "kind": { "$ref": "#/$defs/NodeKind" } } },
                "Position": { "oneOf": [{ "$ref": "#/$defs/PositionRef" }] },
            })
        );
    }

    #[test]
    fn a_value_that_is_not_a_reference_keeps_the_component_path_it_merely_names() {
        // Arrange
        let mut shapes = json!({ "NodeRecord": { "description": "the same shape OpenAPI keeps at #/components/schemas/NodeRecord" } });
        // Act
        point_references_at_shapes(&mut shapes);
        // Assert
        assert_eq!(shapes, json!({ "NodeRecord": { "description": "the same shape OpenAPI keeps at #/components/schemas/NodeRecord" } }));
    }

    #[test]
    fn a_shape_loses_its_prose_at_every_depth_and_keeps_the_field_that_is_called_description() {
        // Arrange
        let mut shapes = json!({
            "NodeRecord": {
                "description": "One node of the graph at a glance.",
                "properties": {
                    "description": { "type": "string", "description": "Prose about this node." },
                    "edge_summary": { "type": "array", "items": { "type": "string", "summary": "One kind." } },
                },
            },
        });
        // Act
        strip_prose_from_each(&mut shapes);
        // Assert
        assert_eq!(
            shapes,
            json!({
                "NodeRecord": {
                    "properties": {
                        "description": { "type": "string" },
                        "edge_summary": { "type": "array", "items": { "type": "string" } },
                    },
                },
            })
        );
    }
}

pub fn attestation_runs_json() -> String {
    let cases: Vec<Value> = runs_cases()
        .into_iter()
        .map(|case| json!({"name": case.name, "canon": Canon { books: case.canon }, "attested": spans(&case.attested), "runs": spans(&case.runs)}))
        .collect();
    serde_json::to_string_pretty(&json!({"cases": cases})).expect("the attestation-run vectors serialise") + "\n"
}

struct RunsCase {
    name: &'static str,
    canon: Vec<CanonBook>,
    attested: Vec<BibleLocusRange>,
    runs: Vec<BibleLocusRange>,
}

fn runs_cases() -> Vec<RunsCase> {
    let sermon_on_the_mount = vec![verses("MAT", 5, 1, 48), verses("MAT", 6, 1, 34), verses("MAT", 7, 1, 29)];
    vec![
        RunsCase {
            name: "a chapter read to its last verse runs on into the next chapter's first",
            canon: vec![book("MAT", "Matthew", &MATTHEW_CHAPTERS)],
            attested: sermon_on_the_mount.clone(),
            runs: vec![range(("MAT", 5, 1), ("MAT", 7, 29))],
        },
        RunsCase {
            name: "without the canon's chapter lengths no chapter runs on into the next",
            canon: Vec::new(),
            attested: sermon_on_the_mount.clone(),
            runs: sermon_on_the_mount,
        },
        RunsCase {
            name: "verses apart in one chapter stay apart",
            canon: vec![book("MRK", "Mark", &MARK_CHAPTERS)],
            attested: vec![verses("MRK", 14, 54, 54), verses("MRK", 14, 66, 72)],
            runs: vec![verses("MRK", 14, 54, 54), verses("MRK", 14, 66, 72)],
        },
        RunsCase {
            name: "within a chapter a verse and the verse after it join",
            canon: Vec::new(),
            attested: vec![verses("2CH", 32, 25, 25), verses("2CH", 32, 26, 26), verses("2CH", 32, 31, 31)],
            runs: vec![verses("2CH", 32, 25, 26), verses("2CH", 32, 31, 31)],
        },
        RunsCase {
            name: "a chapter left before its last verse does not run on",
            canon: vec![book("2KI", "2 Kings", &SECOND_KINGS_CHAPTERS)],
            attested: vec![verses("2KI", 1, 17, 17), verses("2KI", 2, 1, 1)],
            runs: vec![verses("2KI", 1, 17, 17), verses("2KI", 2, 1, 1)],
        },
        RunsCase {
            name: "chapters apart stay apart",
            canon: vec![book("2KI", "2 Kings", &SECOND_KINGS_CHAPTERS)],
            attested: vec![verses("2KI", 1, 17, 17), verses("2KI", 8, 16, 24)],
            runs: vec![verses("2KI", 1, 17, 17), verses("2KI", 8, 16, 24)],
        },
        RunsCase {
            name: "a book's last verse does not run on into the next book",
            canon: vec![book("MAT", "Matthew", &MATTHEW_CHAPTERS), book("MRK", "Mark", &MARK_CHAPTERS)],
            attested: vec![verses("MAT", 28, 20, 20), verses("MRK", 1, 1, 1)],
            runs: vec![verses("MAT", 28, 20, 20), verses("MRK", 1, 1, 1)],
        },
        RunsCase {
            name: "verses given out of order, or twice, make the one run they read as",
            canon: Vec::new(),
            attested: vec![verses("GEN", 1, 3, 3), verses("GEN", 1, 1, 1), verses("GEN", 1, 2, 2), verses("GEN", 1, 2, 2)],
            runs: vec![verses("GEN", 1, 1, 3)],
        },
        RunsCase {
            name: "overlapping and enclosed ranges make the one run they cover",
            canon: Vec::new(),
            attested: vec![verses("GEN", 1, 1, 3), verses("GEN", 1, 2, 5), verses("GEN", 1, 4, 4)],
            runs: vec![verses("GEN", 1, 1, 5)],
        },
    ]
}

const MATTHEW_CHAPTERS: [u16; 28] = [25, 23, 17, 25, 48, 34, 29, 34, 38, 42, 30, 50, 58, 36, 39, 28, 27, 35, 30, 34, 46, 46, 39, 51, 46, 75, 66, 20];
const MARK_CHAPTERS: [u16; 16] = [45, 28, 35, 41, 43, 56, 37, 38, 50, 52, 33, 44, 37, 72, 47, 20];
const SECOND_KINGS_CHAPTERS: [u16; 25] = [18, 25, 27, 44, 27, 33, 20, 29, 37, 36, 21, 21, 25, 29, 38, 20, 41, 37, 37, 21, 26, 20, 37, 20, 30];

fn book(code: &str, name: &str, chapters: &[u16]) -> CanonBook {
    CanonBook { code: code.to_string(), name: name.to_string(), chapters: chapters.to_vec() }
}

fn verses(code: &str, chapter: u16, first: u16, last: u16) -> BibleLocusRange {
    range((code, chapter, first), (code, chapter, last))
}

fn range(from: (&str, u16, u16), to: (&str, u16, u16)) -> BibleLocusRange {
    BibleLocusRange { from: Locus::whole(verse_ref(from)), to: Locus::whole(verse_ref(to)) }
}

fn verse_ref((code, chapter, verse): (&str, u16, u16)) -> VerseRef {
    VerseRef { book: atlas_core::canon::resolve_alias(code).expect("a vector names its book by canon code").0, chapter, verse }
}

fn spans(ranges: &[BibleLocusRange]) -> Vec<TextSpan> {
    ranges.iter().map(|range| TextSpan::of_bible_range(range).expect("a vector's verses are whole")).collect()
}
